In [1]:
import re
import numpy as np
allsentences = ["Sita is a good girl",
                "Hari is a good boy",
                "Mary and Samantha are good girl",
                "Hari is fond of trains",
                "There are many flowers in the garden"]

In [2]:
def word_extraction(sentence):
    ignore = ['a', "the", "is"]
    words = re.sub("[^\w]", " ",  sentence).split()
    cleaned_text = [w.lower() for w in words if w not in ignore]
    return cleaned_text

In [3]:
def tokenize(sentences):
    words = []
    for sentence in sentences:
        w = word_extraction(sentence)
        words.extend(w)
        words = sorted(list(set(words)))
    return words

In [6]:
def generate_bow(allsentences):
    vector = []
    vocab = tokenize(allsentences)
    print("Word List for Document \n{0} \n".format(vocab))
    for sentence in allsentences:
        words = word_extraction(sentence)
        bag_vector = np.zeros(len(vocab))
        for w in words:
            for i,word in enumerate(vocab):
                if word == w:
                    bag_vector[i] += 1
        vector.append(bag_vector)
    return np.array(vector)

In [7]:
vector = generate_bow(allsentences)
print(vector)

Word List for Document 
['and', 'are', 'boy', 'flowers', 'fond', 'garden', 'girl', 'girls', 'good', 'hari', 'in', 'many', 'mary', 'of', 'samantha', 'sita', 'there', 'trains'] 

[[0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0.]]
